name: Bug report
description: Create a report to help us improve
title: "Bug: "
labels: bug
assignees:
  - antond15

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: Version
      description: |
        What release version was this issue encountered on?
        Use the version number, not `latest` or similar useless stuff.
      placeholder: v1.0.2
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: |
        What framework are you getting this error on?
        This resource is framework-standalone, but there may still be framework-specific bugs.
      options:
        - ox_core
        - es_extended
        - qb-core
        - nd_core
        - Other (specify in description)
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        A clear and concise description of what the issue is.
        If you want to paste errors or code, use code blocks.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: "**DETAILED** steps to reproduce the issue."
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Go to '...'
        4. Click on '...'
        5. Scroll down to '...'
        6. See error...
    validations:
      required: true

  - type: checkboxes
    id: confirm
    attributes:
      label: "Confirm the following statements:"
      options:
        - label: "This issue is not a question or a feature request."
          required: true
        - label: "I have provided a **detailed** issue description and **detailed** reproduction steps."
          required: true
